[package]
name = "random_squares"
version = "0.1.0"
authors = ["MaciekTalaska <maciek.talaska@gmail.com>"]
edition = "2018"

[dependencies]
structopt = "0.2.10"
minifb = "0.11.2"
rand = "0.6.5"
tinyppm = { path = "../../tinyppm" }
shared = { path = "../shared" }
