[package]
name = "ppm_viewer"
version = "0.1.0"
authors = ["MaciekTalaska <maciek.talaska@gmail.com>"]
edition = "2018"

[dependencies]
minifb = "0.11.2"
#tinyppm = "0.1"
tinyppm = { path = "../../tinyppm"  }
shared = { path = "../shared" }
